[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm && pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["node build.mjs"]

[start]
cmd = "node --enable-source-maps ./dist/index.mjs"