[settings]
rootDirectory = "artifacts/api-server"

[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile && node build.mjs"

[deploy]
startCommand = "node --enable-source-maps ./dist/index.mjs"